### ISSUE TITLE
Fails to init with Node 7.4

### ISSUE THREAD

**Issue by mattcodez** [milligram/milligram-cli#2]
### Version info

**Milligram:** 0.0.3

**Other (e.g. normalize.css, node.js, npm, bower, browser, operating system) (if applicable):**
Node.js: 7.4.0

### Steps to reproduce

`milligram init new_app`

### Expected behavior

Init new milligram app

### Actual behavior

```
$ milligram init new_app
Cloning into 'new_app'...
Checking connectivity... done
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Socket.Writable.end (_stream_writable.js:478:10)
    at Socket.end (net.js:431:31)
    at Object.<anonymous> (C:\Users\Matt\AppData\Local\Temp\shelljs_1c727ffc7dd99ab7362d:19:20)
exec: internal error
```

**Comment by cjpatoilo** [comment]
Hi @mattcodez. 
Showing "shell.js : internal error". Could you try this again? If the error persists, we can investigate.

Thanks

**Comment by cjpatoilo** [comment]
Hi @mattcodez. Showing "shell.js : internal error". Could you try this again? If the error persists, we can investigate. Thanks.

**Comment by ewa2** [comment]
Bug exists for me, when I'm runing protractor.conf.js
> Yack@0.2.0 pree2e C:\src\Yack
> tsc | npm run webdriver:update -- --standalone


> Yack@0.2.0 webdriver:update C:\src\Yack
> npm run webdriver-manager update "--standalone"


> Yack@0.2.0 webdriver-manager C:\src\Yack
> webdriver-manager "update"

[14:40:40] I/update - chromedriver: file exists C:\src\Yack\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.29.zip
[14:40:40] I/update - chromedriver: unzipping chromedriver_2.29.zip
[14:40:40] I/update - chromedriver: chromedriver_2.29.exe up to date
[14:40:40] I/update - selenium standalone: file exists C:\src\Yack\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.4.0.jar
[14:40:40] I/update - selenium standalone: selenium-server-standalone-3.4.0.jar up to date
[14:40:42] I/update - geckodriver: file exists C:\src\Yack\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.16.1.zip
[14:40:42] I/update - geckodriver: unzipping geckodriver-v0.16.1.zip
[14:40:43] I/update - geckodriver: geckodriver-v0.16.1.exe up to date
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:661:40)
    at Object.write (C:\src\Yack\node_modules\typescript\lib\tsc.js:2230:36)
    at reportDiagnosticSimply (C:\src\Yack\node_modules\typescript\lib\tsc.js:55692:16)
    at reportDiagnostic (C:\src\Yack\node_modules\typescript\lib\tsc.js:55657:9)

> Yack@0.2.0 e2e C:\src\Yack
> npm run protractor tests-config/protractor.conf.js


> Yack@0.2.0 protractor C:\src\Yack
> protractor "tests-config/protractor.conf.js"

**Comment by cjpatoilo** [comment]
@mattcodez Let me know if you need to help again. I will close this issue.
